name: Build Trakt

on:
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.name }}
    secrets:
      ATTIC_ENDPOINT: ${{ secrets.ATTIC_ENDPOINT }}
      ATTIC_CACHE: ${{ secrets.ATTIC_CACHE }}
      ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Trakt
            repository: .
            override-input: self
          - name: SMTCoq
            repository: github:SMTCoq/SMTCoq
            override-input: trakt
          - name: Sniper
            repository: github:SMTCoq/Sniper
            override-input: SMTCoq/trakt

    uses: lafeychine/rocq-utils/.github/workflows/matrix-template.yml@main
    with:
      repository: ${{ matrix.repository }}
      override-input: ${{ matrix.override-input }}
      use-attic: true

  build-success:
    if: ${{ always() }}
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Has the matrix failed?
        if: ${{ needs.build.result != 'success' }}
        run: exit 1
